name: tfc.actions-workspace-vars
description: GitHub Action to update Terraform Cloud Workspace Variables
author: husa-dtg (https://github.com/husa-dtg)
branding:
  icon: play
  color: blue
inputs:
  tfc_host:
    description: The TFC (or TFE) hostname.
    required: false
    default: app.terraform.io
  tfc_token:
    description: The token to use to authenticate with Terraform Cloud.
    required: false
    default: ""
  organization:
    description: The organization in TFC containing the target workspace.
    required: true
    default: ""
  workspace:
    description: The target workspace to receive the credentials.
    required: true
    default: ""
  aws_access_key:
    description: AWS Access Key ID from Vault (assumes Vault standard formatting).
    required: false
    default: ""
  aws_secret_key:
    description: AWS Secret Key ID from Vault (assumes Vault standard formatting).
    required: false
    default: ""
  gcp_svcacct_key:
    description: GCP service account key from Vault (assumes Vault standard formatting).
    required: false
    default: ""
runs:
  using: 'node16'
  main: 'dist/index.js'